xml2rfc_help.jar:
	rm -rf xml2rfc_help
	mkdir xml2rfc_help
	cd xml2rfc_help; xsltproc /opt/local/share/xsl/docbook-xsl/javahelp/javahelp.xsl ../xml2rfc_help.xml
	jar -cvf xml2rfc_help.jar xml2rfc_help

